//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PBO.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PBO.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap add_plant {
            get {
                object obj = ResourceManager.GetObject("add_plant", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;nm&quot;:&quot;your order ready&quot;,&quot;mn&quot;:&quot;&quot;,&quot;layers&quot;:[{&quot;ty&quot;:0,&quot;nm&quot;:&quot;order_ready animation&quot;,&quot;mn&quot;:&quot;&quot;,&quot;sr&quot;:1,&quot;st&quot;:0,&quot;op&quot;:121,&quot;ip&quot;:0,&quot;hd&quot;:false,&quot;cl&quot;:&quot;&quot;,&quot;ln&quot;:&quot;&quot;,&quot;ddd&quot;:0,&quot;bm&quot;:0,&quot;tt&quot;:0,&quot;hasMask&quot;:false,&quot;td&quot;:0,&quot;ao&quot;:0,&quot;ks&quot;:{&quot;a&quot;:{&quot;a&quot;:0,&quot;k&quot;:[250,250,0],&quot;ix&quot;:1},&quot;s&quot;:{&quot;a&quot;:0,&quot;k&quot;:[100,100,100],&quot;ix&quot;:6},&quot;sk&quot;:{&quot;a&quot;:0,&quot;k&quot;:0},&quot;p&quot;:{&quot;a&quot;:0,&quot;k&quot;:[250,250,0],&quot;ix&quot;:2},&quot;sa&quot;:{&quot;a&quot;:0,&quot;k&quot;:0},&quot;o&quot;:{&quot;a&quot;:0,&quot;k&quot;:100,&quot;ix&quot;:11},&quot;r&quot;:{&quot;a&quot;:0,&quot;k&quot;:0,&quot;ix&quot;:10}},&quot;ef&quot;:[],&quot;w&quot;:500,&quot;h&quot;:500,&quot;refId&quot;:&quot;comp_0&quot;,&quot;i....
        /// </summary>
        internal static string bag {
            get {
                return ResourceManager.GetString("bag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap cabut {
            get {
                object obj = ResourceManager.GetObject("cabut", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Cosmos {
            get {
                object obj = ResourceManager.GetObject("Cosmos", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Daisy {
            get {
                object obj = ResourceManager.GetObject("Daisy", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap flower_404 {
            get {
                object obj = ResourceManager.GetObject("flower_404", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap icon {
            get {
                object obj = ResourceManager.GetObject("icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Lavender {
            get {
                object obj = ResourceManager.GetObject("Lavender", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Lily {
            get {
                object obj = ResourceManager.GetObject("Lily", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap loading {
            get {
                object obj = ResourceManager.GetObject("loading", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to !function (t, e) { &quot;object&quot; == typeof exports &amp;&amp; &quot;undefined&quot; != typeof module ? e(exports) : &quot;function&quot; == typeof define &amp;&amp; define.amd ? define([&quot;exports&quot;], e) : e((t = &quot;undefined&quot; != typeof globalThis ? globalThis : t || self)[&quot;lottie-player&quot;] = {}) }(this, (function (exports) {
        ///    &quot;use strict&quot;; function _asyncIterator(t) { var e, r, i, s = 2; for (&quot;undefined&quot; != typeof Symbol &amp;&amp; (r = Symbol.asyncIterator, i = Symbol.iterator); s--;) { if (r &amp;&amp; null != (e = t[r])) return e.call(t); if (i &amp;&amp; null != (e =  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string lottie_player {
            get {
                return ResourceManager.GetString("lottie_player", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;v&quot;:&quot;5.7.4&quot;,&quot;fr&quot;:30,&quot;ip&quot;:0,&quot;op&quot;:21,&quot;w&quot;:1080,&quot;h&quot;:1080,&quot;nm&quot;:&quot;step1&quot;,&quot;ddd&quot;:0,&quot;assets&quot;:[],&quot;layers&quot;:[{&quot;ddd&quot;:0,&quot;ind&quot;:1,&quot;ty&quot;:4,&quot;nm&quot;:&quot;Layer 9 Outlines&quot;,&quot;sr&quot;:1,&quot;ks&quot;:{&quot;o&quot;:{&quot;a&quot;:0,&quot;k&quot;:100,&quot;ix&quot;:11},&quot;r&quot;:{&quot;a&quot;:0,&quot;k&quot;:0,&quot;ix&quot;:10},&quot;p&quot;:{&quot;a&quot;:0,&quot;k&quot;:[539.425,797.822,0],&quot;ix&quot;:2,&quot;l&quot;:2},&quot;a&quot;:{&quot;a&quot;:0,&quot;k&quot;:[50.385,53.564,0],&quot;ix&quot;:1,&quot;l&quot;:2},&quot;s&quot;:{&quot;a&quot;:0,&quot;k&quot;:[500,500,100],&quot;ix&quot;:6,&quot;l&quot;:2}},&quot;ao&quot;:0,&quot;shapes&quot;:[{&quot;ty&quot;:&quot;gr&quot;,&quot;it&quot;:[{&quot;ind&quot;:0,&quot;ty&quot;:&quot;sh&quot;,&quot;ix&quot;:1,&quot;ks&quot;:{&quot;a&quot;:0,&quot;k&quot;:{&quot;i&quot;:[[0,0],[-2.58,-1.497],[0,0],[3.141,0.7....
        /// </summary>
        internal static string plant_0 {
            get {
                return ResourceManager.GetString("plant_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;v&quot;:&quot;5.7.4&quot;,&quot;fr&quot;:30,&quot;ip&quot;:0,&quot;op&quot;:21,&quot;w&quot;:1080,&quot;h&quot;:1080,&quot;nm&quot;:&quot;step1&quot;,&quot;ddd&quot;:0,&quot;assets&quot;:[],&quot;layers&quot;:[{&quot;ddd&quot;:0,&quot;ind&quot;:1,&quot;ty&quot;:4,&quot;nm&quot;:&quot;Layer 9 Outlines&quot;,&quot;sr&quot;:1,&quot;ks&quot;:{&quot;o&quot;:{&quot;a&quot;:0,&quot;k&quot;:100,&quot;ix&quot;:11},&quot;r&quot;:{&quot;a&quot;:0,&quot;k&quot;:0,&quot;ix&quot;:10},&quot;p&quot;:{&quot;a&quot;:0,&quot;k&quot;:[539.425,797.822,0],&quot;ix&quot;:2,&quot;l&quot;:2},&quot;a&quot;:{&quot;a&quot;:0,&quot;k&quot;:[50.385,53.564,0],&quot;ix&quot;:1,&quot;l&quot;:2},&quot;s&quot;:{&quot;a&quot;:0,&quot;k&quot;:[500,500,100],&quot;ix&quot;:6,&quot;l&quot;:2}},&quot;ao&quot;:0,&quot;shapes&quot;:[{&quot;ty&quot;:&quot;gr&quot;,&quot;it&quot;:[{&quot;ind&quot;:0,&quot;ty&quot;:&quot;sh&quot;,&quot;ix&quot;:1,&quot;ks&quot;:{&quot;a&quot;:0,&quot;k&quot;:{&quot;i&quot;:[[0,0],[-2.58,-1.497],[0,0],[3.141,0.7....
        /// </summary>
        internal static string plant_1 {
            get {
                return ResourceManager.GetString("plant_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;v&quot;:&quot;5.7.4&quot;,&quot;fr&quot;:30,&quot;ip&quot;:0,&quot;op&quot;:71,&quot;w&quot;:1080,&quot;h&quot;:1080,&quot;nm&quot;:&quot;step2&quot;,&quot;ddd&quot;:0,&quot;assets&quot;:[],&quot;layers&quot;:[{&quot;ddd&quot;:0,&quot;ind&quot;:1,&quot;ty&quot;:4,&quot;nm&quot;:&quot;Layer 9 Outlines&quot;,&quot;sr&quot;:1,&quot;ks&quot;:{&quot;o&quot;:{&quot;a&quot;:0,&quot;k&quot;:100,&quot;ix&quot;:11},&quot;r&quot;:{&quot;a&quot;:0,&quot;k&quot;:0,&quot;ix&quot;:10},&quot;p&quot;:{&quot;a&quot;:0,&quot;k&quot;:[539.425,797.822,0],&quot;ix&quot;:2,&quot;l&quot;:2},&quot;a&quot;:{&quot;a&quot;:0,&quot;k&quot;:[50.385,53.564,0],&quot;ix&quot;:1,&quot;l&quot;:2},&quot;s&quot;:{&quot;a&quot;:0,&quot;k&quot;:[500,500,100],&quot;ix&quot;:6,&quot;l&quot;:2}},&quot;ao&quot;:0,&quot;shapes&quot;:[{&quot;ty&quot;:&quot;gr&quot;,&quot;it&quot;:[{&quot;ind&quot;:0,&quot;ty&quot;:&quot;sh&quot;,&quot;ix&quot;:1,&quot;ks&quot;:{&quot;a&quot;:0,&quot;k&quot;:{&quot;i&quot;:[[0,0],[-2.58,-1.497],[0,0],[3.141,0.7....
        /// </summary>
        internal static string plant_2 {
            get {
                return ResourceManager.GetString("plant_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;v&quot;:&quot;5.7.4&quot;,&quot;fr&quot;:30,&quot;ip&quot;:0,&quot;op&quot;:71,&quot;w&quot;:1080,&quot;h&quot;:1080,&quot;nm&quot;:&quot;step3&quot;,&quot;ddd&quot;:0,&quot;assets&quot;:[],&quot;layers&quot;:[{&quot;ddd&quot;:0,&quot;ind&quot;:1,&quot;ty&quot;:4,&quot;nm&quot;:&quot;Layer 9 Outlines&quot;,&quot;sr&quot;:1,&quot;ks&quot;:{&quot;o&quot;:{&quot;a&quot;:0,&quot;k&quot;:100,&quot;ix&quot;:11},&quot;r&quot;:{&quot;a&quot;:0,&quot;k&quot;:0,&quot;ix&quot;:10},&quot;p&quot;:{&quot;a&quot;:0,&quot;k&quot;:[539.425,797.822,0],&quot;ix&quot;:2,&quot;l&quot;:2},&quot;a&quot;:{&quot;a&quot;:0,&quot;k&quot;:[50.385,53.564,0],&quot;ix&quot;:1,&quot;l&quot;:2},&quot;s&quot;:{&quot;a&quot;:0,&quot;k&quot;:[500,500,100],&quot;ix&quot;:6,&quot;l&quot;:2}},&quot;ao&quot;:0,&quot;shapes&quot;:[{&quot;ty&quot;:&quot;gr&quot;,&quot;it&quot;:[{&quot;ind&quot;:0,&quot;ty&quot;:&quot;sh&quot;,&quot;ix&quot;:1,&quot;ks&quot;:{&quot;a&quot;:0,&quot;k&quot;:{&quot;i&quot;:[[0,0],[-2.58,-1.497],[0,0],[3.141,0.7....
        /// </summary>
        internal static string plant_3 {
            get {
                return ResourceManager.GetString("plant_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap pupuk {
            get {
                object obj = ResourceManager.GetObject("pupuk", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Rose {
            get {
                object obj = ResourceManager.GetObject("Rose", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;v&quot;:&quot;5.7.4&quot;,&quot;fr&quot;:29.9700012207031,&quot;ip&quot;:0,&quot;op&quot;:74.0000030140818,&quot;w&quot;:246,&quot;h&quot;:111,&quot;nm&quot;:&quot;컴포지션 2&quot;,&quot;ddd&quot;:0,&quot;assets&quot;:[],&quot;layers&quot;:[{&quot;ddd&quot;:0,&quot;ind&quot;:1,&quot;ty&quot;:4,&quot;nm&quot;:&quot;모양 레이어 1&quot;,&quot;sr&quot;:1,&quot;ks&quot;:{&quot;o&quot;:{&quot;a&quot;:0,&quot;k&quot;:100,&quot;ix&quot;:11},&quot;r&quot;:{&quot;a&quot;:0,&quot;k&quot;:0,&quot;ix&quot;:10},&quot;p&quot;:{&quot;a&quot;:0,&quot;k&quot;:[188.5,96.5,0],&quot;ix&quot;:2,&quot;l&quot;:2},&quot;a&quot;:{&quot;a&quot;:0,&quot;k&quot;:[-114.5,-212.5,0],&quot;ix&quot;:1,&quot;l&quot;:2},&quot;s&quot;:{&quot;a&quot;:1,&quot;k&quot;:[{&quot;i&quot;:{&quot;x&quot;:[0.667,0.667,0.667],&quot;y&quot;:[1,1,1]},&quot;o&quot;:{&quot;x&quot;:[0.167,0.167,0.167],&quot;y&quot;:[0.167,0.167,13.333]},&quot;t&quot;:10,&quot;s&quot;:[0,0,100]},{&quot;i&quot;:{&quot;x&quot;:[0.667,0.667,0.667],&quot;y&quot;:[1,1,1]},&quot;o&qu....
        /// </summary>
        internal static string shiny {
            get {
                return ResourceManager.GetString("shiny", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;v&quot;:&quot;5.5.9&quot;,&quot;fr&quot;:29.9700012207031,&quot;ip&quot;:0,&quot;op&quot;:120.0000048877,&quot;w&quot;:200,&quot;h&quot;:200,&quot;nm&quot;:&quot;Planta_0&quot;,&quot;ddd&quot;:0,&quot;assets&quot;:[],&quot;layers&quot;:[{&quot;ddd&quot;:0,&quot;ind&quot;:1,&quot;ty&quot;:4,&quot;nm&quot;:&quot;Shape Layer 1&quot;,&quot;sr&quot;:1,&quot;ks&quot;:{&quot;o&quot;:{&quot;a&quot;:0,&quot;k&quot;:100,&quot;ix&quot;:11},&quot;r&quot;:{&quot;a&quot;:0,&quot;k&quot;:0,&quot;ix&quot;:10},&quot;p&quot;:{&quot;a&quot;:0,&quot;k&quot;:[100,100,0],&quot;ix&quot;:2},&quot;a&quot;:{&quot;a&quot;:0,&quot;k&quot;:[0,0,0],&quot;ix&quot;:1},&quot;s&quot;:{&quot;a&quot;:0,&quot;k&quot;:[100,100,100],&quot;ix&quot;:6}},&quot;ao&quot;:0,&quot;shapes&quot;:[],&quot;ip&quot;:0,&quot;op&quot;:81.0000032991976,&quot;st&quot;:21.0000008553475,&quot;bm&quot;:0},{&quot;ddd&quot;:0,&quot;ind&quot;:2,&quot;ty&quot;:4,&quot;nm&quot;:&quot;1:Base&quot;,&quot;sr&quot;:1,&quot;ks&quot;:{&quot;o&quot;:{&quot;a&quot;:0,&....
        /// </summary>
        internal static string shovel {
            get {
                return ResourceManager.GetString("shovel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap siram {
            get {
                object obj = ResourceManager.GetObject("siram", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap tanah_texture {
            get {
                object obj = ResourceManager.GetObject("tanah_texture", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Tulip {
            get {
                object obj = ResourceManager.GetObject("Tulip", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;v&quot;:&quot;4.8.0&quot;,&quot;meta&quot;:{&quot;g&quot;:&quot;LottieFiles AE 3.0.2&quot;,&quot;a&quot;:&quot;&quot;,&quot;k&quot;:&quot;&quot;,&quot;d&quot;:&quot;&quot;,&quot;tc&quot;:&quot;&quot;},&quot;fr&quot;:30,&quot;ip&quot;:0,&quot;op&quot;:95,&quot;w&quot;:3000,&quot;h&quot;:3000,&quot;nm&quot;:&quot;watering&quot;,&quot;ddd&quot;:0,&quot;assets&quot;:[{&quot;id&quot;:&quot;image_0&quot;,&quot;w&quot;:692,&quot;h&quot;:1315,&quot;u&quot;:&quot;&quot;,&quot;p&quot;:&quot;data:image\/png;base64,iVBORw0KGgoAAAANSUhEUgAAArQAAAUjCAYAAAA3+ravAAAACXBIWXMAAAABAAAAAQBPJcTWAAAAJHpUWHRDcmVhdG9yAAAImXNMyU9KVXBMK0ktUnBNS0tNLikGAEF6Bs5qehXFAAAgAElEQVR4nOzdfXhcd3kn\/O\/vjGS7f418PSTUPEmkKYlByW5lbbfsleXZavSUzV4uSy0tJW3IGo1SoIRCPaIlT8JLfdKElwaKxtA2NEB01DT4IpSV7CxNS9vLo7ZsnoVlJbWbunnrSE6euDjOevRP0 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string water {
            get {
                return ResourceManager.GetString("water", resourceCulture);
            }
        }
    }
}
